List : Hetrogeneous, ordered, mutable and duplicates allowed

In [1]:
ordered_items =["Pizza","Burger", "Pasta","Pizza"]
ordered_items

['Pizza', 'Burger', 'Pasta', 'Pizza']

In [2]:
ordered_items.append("Burger")
ordered_items.extend(["Coke","ICe cream"])

In [3]:
ordered_items

['Pizza', 'Burger', 'Pasta', 'Pizza', 'Burger', 'Coke', 'ICe cream']

In [5]:
ordered_items.remove("Burger") # Remove by name
ordered_items

['Pizza', 'Pasta', 'Pizza', 'Coke', 'ICe cream']

In [6]:
ordered_items.pop() # remove last element
ordered_items

['Pizza', 'Pasta', 'Pizza', 'Coke']

In [7]:
ordered_items.pop(2)
ordered_items

['Pizza', 'Pasta', 'Coke']

In [8]:
ordered_items[:2] #Slicing

['Pizza', 'Pasta']

In [9]:
for item in ordered_items:
    print(item)

Pizza
Pasta
Coke

In [11]:
upper_case = [item.upper() for item in ordered_items]
upper_case

['PIZZA', 'PASTA', 'COKE']

Dictionary : Key-value, hetrogeneous, no order, mutable and duplicate key not allowed.

In [26]:
customer = {"name" : "Raj",
            "age": 22,
            "city":"Mumbai"}
customer

{'name': 'Raj', 'age': 22, 'city': 'Mumbai'}

In [27]:
customer["name"]

'Raj'

In [28]:
customer.get("age")

22

In [29]:
customer["phone"] = 999999991
customer["age"] = 23

In [30]:
customer

{'name': 'Raj', 'age': 23, 'city': 'Mumbai', 'phone': 999999991}

In [31]:
del customer["age"]
customer

{'name': 'Raj', 'city': 'Mumbai', 'phone': 999999991}

In [32]:
for key, value in customer.items():
    print(key,value)

name Raj
city Mumbai
phone 999999991

Sets : unordered, Unique, not mutable

In [34]:
cuisines = {"Indian","Chinese","Italian","Indian"}
cuisines

{'Chinese', 'Indian', 'Italian'}

In [35]:
cuisines.add("Mexican")
cuisines

{'Chinese', 'Indian', 'Italian', 'Mexican'}

In [36]:
cuisines.discard("Chinese")

In [37]:
cuisines_set1 = {"Indian","Chinese"}
cuisines_set2 = {"Indian", "Mexican","Italian"}

In [38]:
cuisines_set1.union(cuisines_set2) # Union

{'Chinese', 'Indian', 'Italian', 'Mexican'}

In [39]:
cuisines_set1.intersection(cuisines_set2)  #intersection

{'Indian'}

In [40]:
cuisines_set1.difference(cuisines_set2) # difference

{'Chinese'}

Tuple: Ordered, Immutable

In [41]:
location =(19.0700,72.8777)
lat, lon = location # unpacking
print(lat, lon)

19.07 72.8777

In [ ]:
t1 = (1,) # single value declaration in tuple

Case study for datasets

In [ ]:
order ={
    "order_ id" : 101,
    "Customer":{
        "name":"Rahul",
        "age":22,
        "city":"Mumbai"
    },
    "items" : ["Pizza","Burger","Pizza"],
    "cuisines": {"Italian","Indian"},
    "location":(19.0766, 72.8777)
}

In [42]:
import numpy as np
import pandas as pd

In [43]:
dtypes = pd.DataFrame({
    'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32',
             'int64', 'uint64', 'float16', 'float32', 'float64',
             'float128', 'complex64', 'complex128', 'bool',
             'object', 'string_', 'unicode_'],
    'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4',
                  'i8', 'u8', 'f2', 'f4 or f', 'f8 or d',
                  'f16 or g', 'c8', 'c16', '',
                  'O', 'S', 'U']
})

In [45]:
dtypes

          Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool
15      object         O
16     string_         S
17    unicode_         U

In [46]:
arr = np.array([12,3,4,5], dtype='f4')
arr

array([12.,  3.,  4.,  5.], dtype=float32)

In [47]:
arr.dtype

dtype('float32')

In [48]:
np.array([1+2j, 2-4j], dtype=np.complex64) #array of complex number

array([1.+2.j, 2.-4.j], dtype=complex64)

In [49]:
np.array([0,1,1], dtype=bool) #array of boolean

array([False,  True,  True])

In [50]:
np.array([0,1,1], dtype=np.bool_)

array([False,  True,  True])

In [51]:
np.array(['abc','cde'], dtype='S3')

array([b'abc', b'cde'], dtype='|S3')

Series: 1-D labelled array that can store multiple data types

In [52]:
s1 = pd.Series([1, "Amit", 3.5, "Hello"])
s1

0        1
1     Amit
2      3.5
3    Hello
dtype: object

In [53]:
s1 = pd.Series([1, "Amit", 3.5, "Hello"], index=["a","b","c","d"]) #Custom index
s1

a        1
b     Amit
c      3.5
d    Hello
dtype: object

In [54]:
emp = {"amit":10000,"sai":40000, "ram":50000,"Tom":45000}
list = pd.Series(emp)
list

amit    10000
sai     40000
ram     50000
Tom     45000
dtype: int64

Dataframe: 2-D combination of rows & column

In [57]:
student ={
    'Name' : ["Amit","Bob","Tom"],
    'Marks': [78,56,89]
}
df = pd.DataFrame(student)
df

   Name  Marks
0  Amit     78
1   Bob     56
2   Tom     89

In [59]:
df['Grade'] = ['A','B','A']
df

   Name  Marks Grade
0  Amit     78     A
1   Bob     56     B
2   Tom     89     A

In [62]:
df = df.drop('Grade', axis=1)

In [63]:
df

   Name  Marks
0  Amit     78
1   Bob     56
2   Tom     89

In [65]:
df.rename(columns={'Name':'Title'}, inplace=False)

  Title  Marks
0  Amit     78
1   Bob     56
2   Tom     89

In [66]:
df['Marks'] = df['Marks'].apply(lambda x: x+5)

In [67]:
df

   Name  Marks
0  Amit     83
1   Bob     61
2   Tom     94